CREATE TABLE IF NOT EXISTS images (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    path TEXT,
    type VARCHAR(50),
	width INT, 
	height INT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);