name: Internal Employee CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js for backend
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install backend dependencies
      run: |
        cd internal-employee-directory
        cd backend
        npm install

    - name: Lint backend code
      run: |
        cd internal-employee-directory
        cd backend
        npm run lint

    - name: Run backend tests
      run: |
        cd internal-employee-directory
        cd backend
        npm test

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js for frontend
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install frontend dependencies
      run: |
        cd internal-employee-directory
        cd frontend
        npm install

    - name: Lint frontend code
      run: |
        cd internal-employee-directory
        cd frontend
        npm run lint

    - name: Run frontend tests
      run: |
        cd internal-employee-directory
        cd frontend
        npm test